src/api.ts
src/components/Filter.tsx
src/components/common/activity/activity.tsx
src/utils/use-local-storage.tsx

Improve the browsing experience for the Activity list by using `@tanstack/react-query` so that there is some caching.

feat: Add react-query to Activity list

---

src/api.ts
src/components/Area.tsx

Improve the browsing experience of the area page by using `@tanstack/react-query` so that we have some caching and data refresh.

feat: Introduce react-query to the area page

---

src/api.ts
src/components/Filter.tsx
src/components/Sector.tsx

Use local caching on the sector page. This makes it much better to navigate around within an area during a session which may have flaky internet access.

feat: Improve sector data-fetching

---

src/@types/buldreinfo/index.d.ts
src/api.ts
src/components/Problem.tsx
src/components/common/comment-modal/comment-modal.tsx
src/components/common/tick-modal/tick-modal.tsx

The problem/route detail page is full of flashing loading spinners as the page is used. This is really disruptive and that's less than ideal.
This change improves that and makes it seamless/magic to add comments, tick problems, add to-dos, etc.

chore: Improve the data fetching for Problems

---

src/components/Problem.tsx
src/components/common/tick-modal/tick-modal.tsx

This was missed in the previous invalidation pass. This causes cache inconsistency issues.

fix: Invalidate after ticking (or unticking)

---

src/@types/buldreinfo/index.d.ts
src/components/Problem/Problem.tsx
src/components/Problem/ProblemComments/ProblemComments.tsx
src/components/Problem/ProblemComments/index.ts
src/components/Problem/ProblemTicks/ProblemTicks.tsx
src/components/Problem/ProblemTicks/index.ts
src/components/Problem/ProblemsOnRock/ProblemsOnRock.tsx
src/components/Problem/ProblemsOnRock/index.ts
src/components/Problem/index.ts
src/components/Sector.tsx
src/components/common/activity/activity.tsx
src/utils/componentDecorator.tsx

The `Problem` component is all in one file, and has multiple components. This giant pile of code is hard to read and maintain. This change moves the subcomponents out to separate files so that they're easier to maintain & traverse. Maybe we can even add tests and storybook story definitions some day!

chore: Refactor the Problem component

---

webpack.common.js

The source code for this project isn't secret - let's enable source map generation (& publication) so that tools (eg, [Sentry]) can be even better.
[sentry]: https://sentry.io

Enable sourcemap generation

---

src/components/AreaEdit.tsx
src/components/ProblemEdit.tsx
src/components/SectorEdit.tsx
src/components/common/VisibilitySelector/VisibilitySelector.tsx
src/components/common/VisibilitySelector/index.ts

This form field was triplicated throughout the app - we can centralize it and its logic to avoid the repetition.

Extract a VisibilitySelector control

---

src/components/Permissions.tsx

feat: Add search bar to permissions to make it easier to find users

---

src/components/ProblemEdit.tsx
src/components/common/image-upload/image-upload.tsx
src/components/common/user-selector/user-selector.tsx

Continue bringing type safety to the app by introducing types at the leaf nodes -- `UserSelector`, in this case. This change also splits it into `UserSelector` and `UsersSelector` to make the two cases more explicit and have stronger typing in the callbacks.

Add typing to UserSelector

---

src/components/common/image-upload/image-upload.tsx
src/components/common/image-upload/video-embedder.tsx

Type the `VideoEmbedder` component to make it easier to maintain & work with.

Add typing to VideoEmbedder

---

src/api.ts
src/components/AreaEdit.tsx
src/components/ProblemEdit.tsx
src/components/ProblemEditMedia.tsx
src/components/SectorEdit.tsx
src/components/common/comment-modal/comment-modal.tsx
src/components/common/image-upload/image-upload.tsx

This component was really tough to follow (and it was doing some pretty sketchy direct-manipulation of objects). This change adds typing and cleans up some of the internal logic to make it more React-y.

Add typing to ImageUpload component

---

package.json
src/@types/buldreinfo/swagger.d.ts
src/api.ts
src/components/Area.tsx
src/components/Problem/ProblemsOnRock/ProblemsOnRock.tsx
src/components/Sector.tsx
src/components/common/activity/activity.tsx
src/components/common/leaflet/leaflet.tsx
src/components/common/leaflet/markers.tsx
yarn.lock

There was a typing area in the Area component, and I fixed similar issues that would likely happen in problems/sectors, too.

Fix typing error in useArea(..)

---

.babelrc
.eslintrc.js
.storybook/main.ts
.storybook/preview-head.html
.storybook/preview.ts
package.json
src/components/common/widgets/WeatherIcon.stories.tsx
src/components/common/widgets/widgets.tsx
src/utils/storybook.d.ts
webpack.common.js
yarn.lock

[Storybook] is a fantastically-useful utility which allows components to be rendered and tested in isolation. This makes it possible inject problematic data, force temporary states (eg, loading), and cover hard-to-remember scenarios.
This change introduces Storybook to the repo, and adds some very basic stories to demonstrate that it's functional. Stories for the more complicated components will come in future PRs in order to keep this practical to review.
[storybook]: https://storybook.js.org/

chore: Introduce Storybook

---

src/components/common/FilterForm/FilterForm.tsx

When filtering for a problem / route, it can be overwhelming (to the UI) if the user has many (or all) of the areas enabled on their profile. In cases like these, put a cap on the maximum size of the areas shown -- by default. If the user wishes to, they're able to expand (and then collapse) the area list to avoid nested scrolling.

Collapse the area list with many areas

---

src/@types/buldreinfo/swagger.d.ts

Re-run `yarn swagger` and commit the updated files.

Update swagger definitions

---

package.json
src/components/Sector.tsx
src/components/common/leaflet/geo-utils.tsx
src/components/common/leaflet/leaflet.tsx
src/components/common/leaflet/markers.tsx
src/components/common/widgets/widgets.tsx
src/utils/componentDecorator.tsx
src/utils/useRedirect.tsx
yarn.lock

Continue the march towards TypeScript strictness by enabling `strict: true` in `tsconfig.json`, doing a build, and then fixing some errors.
This focused on the `Sector` component, and spiraled a little bit from there.
More to come in future PRs.

chore: Fix more TypeScript strict mode errors

---

src/components/common/FilterForm/GradeSelect/GradeSelect.tsx

Reverts jossi87/climbing-web#157
This is broken and should be fixed properly.

Revert "fix: Flip the Grades slider"

---

package.json
src/api/operations.ts
src/api/utils.ts
src/components/Problem/Problem.tsx
src/components/Problems/reducer.ts
src/components/common/tick-modal/tick-modal.tsx
src/components/common/widgets/widgets.tsx
src/utils/lazyRetry.ts
src/utils/polyline.ts
yarn.lock

The march towards `strict: true` continues with fixing another 100 violations.
More to come!

chore: Fix more TypeScript errors

---

package.json
src/@types/buldreinfo/index.d.ts
src/api/hooks.ts
src/components/Area.tsx
yarn.lock

Continue the march towards `strict: true` in `tsconfig.json` by eliminating another batch of errors. This change primarily focuses around the `Area` component.

chore: Fix more strict TypeScript errors

---

src/components/About.tsx

Definition:
Statue
To stand as still as a statue is to stand absolutely still, a statue
being a sculpture, after all. A statue is a specific kind of sculpture,
one that clearly represents a person, an animal, or other living
creature.
Statute
A statute is a formal law or rule. Whether it's enacted by a government,
company, or other organization, a statute is typically written down.

Statue vs. Statute
