jossi87/climbing-web

package.json
src/components/Browse.tsx
src/components/Swagger.tsx
src/components/common/profile/profile-media.tsx
yarn.lock

There are a few TypeScript errors that have snuck in. This change fixes them (as verified with `yarn tsc`)

chore: Fix TypeScript errors

---

package.json
src/api.ts
src/components/About.tsx
src/components/Browse.tsx
src/components/ContentGraph.tsx
src/components/Dangerous.tsx
src/components/Frontpage.tsx
src/components/Toc.tsx
src/components/Trash.tsx
src/components/WebcamMap.tsx
src/index.tsx
yarn.lock

Using the app is a little painful today - every time you navigate to a new page, the data must be fetched anew. This works _okay_ on a device on Wi-Fi, but this can be really irritating when out at the crags. Out there, cell service is much less reliable and can leave one stuck looking at a loading screen.
Instead, introduce `@tanstack/react-query`, which is a modern hook-based state management solution for data liveliness. This allows us to show stale data and refresh it in the background. In the future, it would allow us to plug in proper offline support, too.
This PR is a **first pass** over some of the pages. Specifically, only the ones which make `GET` requests without parameters. The rest shouldn't be a problem to follow the same pattern, but I didn't want to rewrite the entire app …

feat: Introduce @tanstack/react-query

---

src/api.ts
src/components/Area.tsx
src/components/Sector.tsx
src/components/common/todo/todo.tsx
src/components/common/top/top.tsx

Continue the data-fetching improvement crusade with improve the data-fetching experience with the introduction of
`@tanstack/react-query` to fetching of the Top and Todo tabs.
This prevents loading-flickering on subsequent navigations.

feat: Improve data fetching for Top & Todo

---

src/api.ts
src/components/Area.tsx

If the requested area can't be found (invalid ID, insufficient permissions, etc), a message should be shown to the end user. This already happens today. However it does so in the API layer.
This change moves the error-detection (& string selection) up to the UI layer. In addition to being a bit more "normal", it also lets the data-fetching be simpler.

feat: Move /areas error from API to UI

---

src/components/Area.tsx
src/components/AreaEdit.tsx
src/components/Browse.tsx
src/components/Filter.tsx
src/components/Problem.tsx
src/components/ProblemEdit.tsx
src/components/Sector.tsx
src/components/SectorEdit.tsx
src/components/Sites.tsx
src/components/WebcamMap.tsx
src/components/common/leaflet/leaflet.tsx
src/components/common/leaflet/markers.tsx
src/components/common/leaflet/polygons.tsx
src/components/common/profile/profile-statistics.tsx
src/components/common/profile/profile-todo.tsx

The `Leaflet` components need a `navigate` instance. However, instead of plumbing it in from the outside (at each callsite), those components can obtain (& own) their own instances using `useNavigate()`.

chore: Don't plumb around navigate

---

src/App.tsx
src/components/Filter.tsx
src/components/Navigation.tsx
src/components/common/meta/index.ts
src/components/common/meta/meta.tsx

Instead of fetching `/meta` several times throughout the app, fetch it once and expose it to all components through a context provider.
> NOTE: There is still a remaining `/meta` call through the area-edit
>       function. This will be removed when that API gets cleaned up.

feat: Provide /meta to the whole app

---

src/App.tsx
src/components/Filter.tsx
src/components/Header.tsx
src/components/Navigation.tsx
src/components/Navigation/Navigation.css
src/components/Navigation/Navigation.tsx
src/components/Navigation/index.ts
src/components/common/meta/index.ts
src/components/common/meta/meta.tsx

The current navigation header isn't terribly responsive to device sizes.
It would be nice to work well on small devices (especially with
touch-input) as well as on large devices.
This change makes the top navigation bar responsive and attempts to be
more user-friendly. Specifically:
1. On wide screens, all of the items are shown, with icons and text.
2. On less-wide screens, some of the "secondary" items are collapsed to
just icons.
3. On even smaller screens, all of the items will be reduced to just
icons.
4. On very small screens, it will take on a multi-line format, with the
first line being the home button and search bar, and the rest of the
items being slotted into however many rows are necessary. Devices of
this size are generally touch-input devices, so the text is included …

feat: Add a responsive navigation header

---

src/components/common/media/svg.tsx

I've added a white, thin border to the id-label of the selected route in the topo pic for enhanced visibility like discussed in issue 
#18.

border added to the id-label for the selected route in the topo pic

---

src/components/common/media/svg.tsx

svg attributes inside react must be camelCase, not hyphened. Fixed previous addition from stroke-width to strokeWidth

fix: svg attributes inside react code must be camelCase

---

package.json
src/api.ts
src/components/AreaEdit.tsx
src/components/ProblemEdit.tsx
src/components/SectorEdit.tsx
src/components/common/chart-grade-distribution/chart-grade-distribution.tsx
src/index.tsx
yarn.lock

When making an edit to a resource (area, sector, problem), we need to make sure to invalidate the cache. Otherwise, we run the risk of showing the user stale data when they go back to the resource's page.
This is a temporary stop-gap -- in the future, we should go all-in on `useMutation(..)`, which will modify the cache and prevent a refetch at all. However, that'll take too long, so let's land this first.

fix: Invalidate the cache after edits

---

src/api.ts
src/components/MediaSvgEdit.tsx
src/components/SvgEdit.tsx
src/components/common/widgets/widgets.tsx

After an image is edited, we send the user back to where they came from (likely the sector that they were viewing). However, the data that is shown on the screen is the _previous_ data, living in RAM.
In order to refetch this, we do a very heavy-handed refetch of **all** sectors. This is necessary because when we're editing an image, we don't know which sector(s) that image belongs to.
This is better than the bug, but it's not ideal.

fix: Refetch sectors after editing an image

---

src/components/AreaEdit.tsx
src/components/Permissions.tsx
src/components/ProblemEdit.tsx
src/components/ProblemEditMedia.tsx
src/components/SectorEdit.tsx
src/components/SvgEdit.tsx

Until everything is migrated to using `@tanstack/react-query`, we're running into consistency problems when it comes to mutations. For now, whenever there's a mutation, just invalidate everything in the the local cache.

fix: Do some heavy-handed cache invalidation

---

src/api.ts
src/components/Area.tsx
src/components/AreaEdit.tsx
src/components/DataReloader/DataReloader.tsx
src/components/DataReloader/index.ts
src/components/Permissions.tsx
src/components/Problem.tsx
src/components/ProblemEdit.tsx
src/components/ProblemEditMedia.tsx
src/components/Sector.tsx
src/components/SectorEdit.tsx
src/components/SvgEdit.tsx
src/components/Trash.tsx
src/components/common/comment-modal/comment-modal.tsx
src/components/common/media/media.tsx
src/components/common/profile/profile-media.tsx
src/components/common/profile/profile-settings.tsx
src/components/common/search-box/search-box.tsx
src/components/common/tick-modal/tick-modal.tsx
src/index.tsx

The current data model has lots of interconnectedness - a field which can be mutated in one mutation can be replicated in several other queries. This creates a problem where a mutation can inadvertently result in stale data in the UI.
To address this - without throwing away the benefits of the local datastore - we introduce a utility to guarantee data consistency: invalidate (or refetch) everything. This can be overridden query-by-query in the API, which should let us migrate them one at a time. The goal here, however, is to ensure that everything remains healthy.

fix: Invalidate the cache on mutations

---

src/components/Area.tsx
src/components/Areas.tsx
src/components/Graph.tsx
src/components/Profile.tsx
src/components/Sector.tsx
src/components/common/chart-grade-distribution/chart-grade-distribution.tsx
src/components/common/profile/profile-media.tsx
src/components/common/profile/profile-settings.tsx
src/components/common/profile/profile-statistics.tsx
src/components/common/profile/profile-todo.tsx

Some components were still using access tokens, provided to them from the outside. This is not necessary, and access tokens can be retrieved locally using the `useAccessToken()` hook.

chore: Remove plumbed-through access tokens

---

src/@types/buldreinfo/index.d.ts
src/api.ts
src/components/Profile.tsx
src/components/common/profile/profile-media.tsx
src/components/common/profile/profile-statistics.tsx
src/components/common/profile/profile-todo.tsx

Adopt `@tanstack/react-query` throughout the `/profile/*` pages to make the browsing experience better.

feat: Introduce data-fetching to the profile pages

---

src/api.ts
src/components/Area.tsx
src/components/Problem.tsx
src/components/Sector.tsx
src/components/common/profile/profile-todo.tsx

When a problem is added (or removed) from a user's to-do list, a few select parts of the data store need to be invalidated & requeried (rather than everything):
- `/problem` (for the relevant problem)
- `/sectors` (for the relevant sector)
- `/areas` (for the relevant area)
- `/profile/todo` (for the user's to-do list)
This is a slight optimization to the current system, where the entire data model (all previously-fetched data) would be refetched.

fix: Only refetch what's necessary for todos

---

src/components/Profile.tsx

If the user navigates to a profile page, they can then click around between the different tabs: to-do, media, etc. However, if they use their browser's back/forward buttons, the page doesn't change!
This fixes that and makes everything work as it should (by removing complexity! 🎉)

fix: Support history on the profile tabs

---

src/api.ts
src/components/Area.tsx
src/components/Problem.tsx
src/components/Sector.tsx
src/utils/useRedirect.tsx

When an item (area, sector, problem) was moved to the trash, it kicked off a race condition which would leave the user in an odd state. The sequence of events would look like this:
1. User navigates to `/area/123`
2. User starts to edit the area (`/area/edit/123`)
3. User marks the area for deletion
4. User clicks save
5. A `POST` request is sent to trash the item
6. The user is navigated - with in-app navigation - to the home page (`/`).
7. Under the hood, the `/area/123` query was refetched to keep the data consistent
8. When the response for loading the data comes in, the API layer notices that the server the user should be redirected to `https://.../area/123` and **moves the browser** to the new location
9. The new location (`https://.../area/123`) attempts to load the now-deleted …

fix: Odd redirect bug when moving items to trash

---

src/api.ts
src/components/AppRoutes.tsx
src/components/Area.tsx
src/components/Problem.tsx
src/components/ProblemEdit.tsx
src/components/Sector.tsx
src/components/SectorEdit.tsx
src/components/SvgEdit.tsx
src/components/common/media/media-modal.tsx

In a few places, the URL needed to store two IDs. These were generally encoded a `{firstId}-{secondId}` and then parsed at runtime (often several times).
Instead, define new routes so that they can be provided as `/{firstId}/{secondId}`, like a standard URI.

chore: Remove encoded IDs from URLs

---

package.json
src/index.tsx
yarn.lock

Add Sentry integration so that we can get alerts of errors when they happen in production, even if the user doesn't report it.

feat: Add Sentry integration

---

src/components/AppRoutes.tsx
src/components/AreaEdit.tsx
src/components/AuthContainer/AuthContainer.tsx
src/components/AuthContainer/index.ts
src/components/MediaSvgEdit.tsx
src/components/Permissions.tsx
src/components/ProblemEdit.tsx
src/components/ProblemEditMedia.tsx
src/components/SectorEdit.tsx
src/components/SvgEdit.tsx
src/components/Trash.tsx

Introduce an `AuthContainer` component to centralize the gate-keeping logic ("is this user logged in? do they have the right permissions?") which was previously scattered throughout the app and duplicated onto each page.
As a bonus, this makes it easier to see which routes need which permissions, by looking at the static declarations in `AppRoutes`.

feat: Centralize permissions-checking

---

src/index.tsx

Set the `environment` part of Sentry to correctly classify errors (errors for developers shouldn't be grouped with errors in production).
This also turns off replays for non-error sessions, as I don't think we need those.

Set the Sentry environment

---

src/components/About.tsx
src/components/Area.tsx
src/components/AreaEdit.tsx
src/components/Areas.tsx
src/components/Dangerous.tsx
src/components/Donations.tsx
src/components/Filter.tsx
src/components/Frontpage.tsx
src/components/Graph.tsx
src/components/Permissions.tsx
src/components/PrivacyPolicy.tsx
src/components/Problem/Problem.tsx
src/components/ProblemEdit.tsx
src/components/Problems.tsx
src/components/Profile.tsx
src/components/Sector.tsx
src/components/SectorEdit.tsx
src/components/Sites.tsx
src/components/Ticks.tsx
src/components/Trash.tsx
src/components/Webcams.tsx
src/components/common/meta/meta.tsx

Virtually all of the pages used the same title format:
some string | {meta.name}
This was replicated on every individual page. Instead, we can utilize the `titleTemplate` prop from `Helmet` and save ourselves the construction on every page.
On the few pages which didn't use this, the `titleTemplate` was overridden.

Use Helmet's titleTemplate to templatize the titles

---

src/components/Area.tsx
src/components/Problem/Problem.tsx
src/components/Problem/ProblemComments/ProblemComments.tsx
src/components/Profile.tsx
src/components/Sector.tsx
src/components/common/media/media-modal.tsx
src/components/common/media/media.tsx
src/components/common/meta/meta.tsx
src/components/common/profile/profile-media.tsx

Take another pass over the codebase and remove more plumbing of meta properties (as they can be fetched where needed with `useMeta()`). Specifically, this focused on `isAdmin`, but `isBouldering` and `isClimbing` were cleaned up along the way.

One more pass at removing meta-plumbing

---

src/components/Problems.tsx
src/components/common/SmartLink/SmartLink.tsx
src/components/common/SmartLink/index.ts
src/components/common/profile/profile-todo.tsx

Our telemetry shows that the slowest page (on average, 95th percentile)
to laod is `/problem/*`. Virtually all of the sessions that are slowest
begin with a pageload event -- someone is navigating directly to
`/problem/:problemId`.
One possibility is that they're being sent links or clicking on
bookmarks. This is possible (and, indeed, probable).
Another possibility to enter this flow is from the `/problems` page.
From here, navigating to any problem opens a new tab -- which requires
reloading all of the network-fetched resources. Static assets like CSS,
HTML, and JS are cached. However, the lazily-loaded content is not
fetched.
This change makes the problems default to opening in the same tab. With
the new data layer, this makes navigation forward and backward much less
costly. If …

Don't open problems in a new window/tab

---

src/components/Profile.tsx
src/components/common/media/media-modal.tsx

There are two issues fixed here:
1. When navigating to a profile for a user that doesn't have both first and last names provided, the UI can break because `undefined` is attempted to be rendered in the `<title>`, which React is unhappy about.
2. If the media item hasn't been loaded yet (eg, a direct link to the media item) then `NaN` will be computed as the seek-to amount, and this isn't allowed.
Not to put any profile on blast, this particular URL has both of these problems and makes a great test case: https://buldreinfo.com/user/2615/media

Fix issues with media on profiles

---

webpack.config.webpackbundleanalyzer.js

In order to diagnose the size of our bundled assets, we need a functioning `webpack-bundle-analzyer`. This fixes our outdated config and makes it work again 🎉

Fix the bundle analyzer

---

src/components/AppRoutes.tsx
src/utils/lazyRetry.ts

Do a lazy-load with fallback
When the app is built, it's split into several different chunks, in
order to reduce initial load time (downloading and parsing ≥ 3MB of
JavaScript can be very taxing for some networks and browsers). However,
this creates issues when deploying new versions, as these chunk names
are hashed and change for almost every build.
This means that if a user is using the app, and the CI/CD process
deploys a new version, they might be hit with an error screen when they
browse to a new page. This is very uncool.
What this change does is watch the chunk-loading process and, if that
fails, reloads the page. This should be enough to allow the user to
recover, as they'll get a fresh set of chunk-pointers loaded when the
newly-deployed app is loaded. It's not a _great_ …

Do a lazy-load with fallback

---

package.json
src/api.ts
yarn.lock

The type definitions were missing for the `isomorphic-fetch` package, which made it hard to work with. Adding these types also uncovered a few edge-cases which would've resulted in crashes.

Add types for isomorphic-fetch

---

src/@types/buldreinfo/index.d.ts
src/api.ts
src/components/ProblemEdit.tsx
src/components/Trash.tsx

Update the trash page (`/trash`) to use the mutations & queries pattern. This is a rather pointless change, but it provided an opportunity to fix up the typing around `usePostData(..)` and `useData(..)`, which was a bit hodge-podge.
This also fixes a small error wherein we trigger fetches of known-deleted resources when a problem is moved to the trash (we should apply this pattern to other media types, too).

Rework the trash page

---

src/@types/buldreinfo/index.d.ts
src/api.ts
src/components/common/search-box/search-box.tsx

Searches use POST (rather than the more-common GET) request, and we requery everything on mutations (by default) to ensure cache consistency. However, this means that searching does a _ton_ of revalidation.
Disable this behavior when searching .. and make some searchbox cleanups along the way.

Don't invalidate everything for a search query

---

src/components/Profile.tsx
src/components/common/profile/profile-statistics.tsx

It's possible for the profile data to fail to load - I don't know how, but we have at least one crash in the wild that happened. If this happens, let's record the failure (so that we can investigate) and show the user a friendly error message instead of crashing the app.

Don't crash on failing profile data

---

src/api.ts
src/components/Problems/Problems.tsx

On mobile devices, a load of `/problems` can take a nontrivial amount of time -- especially if the user has chosen to show the data for many areas.
While this is ongoing, continue showing the loading progress to give the user an indication that something is happening.

Show loading indicator until data is processed

---

src/components/Areas.tsx
src/components/Navigation/Navigation.tsx
src/components/Problems/Problems.tsx
src/components/common/FilterForm/FilterForm.tsx
src/components/common/HeaderButtons/HeaderButtons.tsx
src/components/common/HeaderButtons/index.ts

The header-with-buttons pattern is used in a few places, and there are some edge cases to handle when it comes to responsive layouts. This change introduces a `<HeaderButtons />` component to ensure that it's handled the same way throughout the app.
| Device | Screenshot |
|:---:|:---|
| mobile | ![image](https://github.com/jossi87/climbing-web/assets/418560/efda7934-38f2-4cae-a4a5-47b1e7c927d0) |
| wider | ![image](https://github.com/jossi87/climbing-web/assets/418560/4d282ea7-2326-45cf-8436-62de18c73723) |
| desktop | ![image](https://github.com/jossi87/climbing-web/assets/418560/db4b12f7-36ed-461c-800e-73ad73e87ccc) |

Standardize the header button pattern

---

src/components/Problems/Problems.tsx
src/components/Problems/reducer.ts
src/components/common/FilterForm/GradeSelect/GradeSelect.tsx
src/components/common/meta/meta.tsx
src/index.tsx

On initial load, the filter won't filter out based on grade levels. This is because the grade information is only set when the `<GradeSelect />` component is rendered .. but it's not rendered by default.
Fix this by listening for the grade information to change and always keeping the state updated.
This also introduces a `useGrades()` hook to make this information easier throughout the app (though this cleanup has not yet been performed).

Fix an issue with the filter not always applying

---

src/components/Problems/reducer.ts

The admin & superadmin filters can be used in conjunction, and they shouldn't override each other. Additionally, they shouldn't override the other filters that might be applied (eg, grades or types).

Correct the admin/superadmin filter logic

---

src/components/Problems/reducer.ts

Prior to this change, when "only admin" or "only superadmin" options were enabled, areas & sectors which were admin/superadmin restricted would be shown -- even if all of their children were hidden.
This change brings the area/sector logic in line with the rest of the filter behavior.

Hide all empty areas/sectors

---

src/@types/buldreinfo/index.d.ts
src/api.ts
src/components/Profile.tsx
src/components/common/profile/profile-settings.tsx

The page which lets you control which regions to show under the same site was a bit annoying to use - it would reload every time something was changed, making it really flashy and awkward.
This is no longer necessary, as we can reload the data in the background. However, this change goes one step further and directly modifies the local datastore to avoid an extra round-trip -- mainly just for fun and practice :)

Rework the /user/<uid>/settings page

---

src/components/Problems/reducer.ts

Toggling on the "Only admin" filter should toggle off (if set) the "Only superadmin" filter (and likewise for the other way around).

Make the admin/superadmin filter exclusive

---

src/components/common/search-box/search-box.tsx

When the `SearchBox` is rendered in the `<Menu.Item>`, it gets bogus `children` passed in. This is harmless except it prints a warning in the console and that bugs me.

chore: Remove a console warning from SearchBox

---

package.json
yarn.lock

We use the `file-saver` package to serve text blobs to the user (eg, downloading Excel files). This package has types defined in the `@types/file-saver` package.

chore: Add @types/file-saver

---

src/components/common/search-box/search-box.tsx

When searching, often you get good enough results without typing the whole query. In this case, you want to be able to click on a result and go there. However, sometimes you want to go to another result.
It would be great to have the search box keep the previously-typed query so that the results are already preloaded for rapid navigation.
This change does exactly that.

Restore search partial-query persistence

---

src/components/Areas.css
src/components/Areas.tsx

The current codebase caps the amount of text shown for area descriptions by chopping to an arbitrary number of characters.
Instead, we can use CSS line clamping to cap it to the desired number of lines and ellipsize automatically.
NOTE: `line-clamp` is still a developing standard, but it's supported [nearly everywhere](https://caniuse.com/css-line-clamp).

Use CSS line-clamping for text limiting

---

src/api.ts
src/components/MediaSvgEdit.tsx
src/components/common/media/media-modal.tsx
src/components/common/media/media.tsx
src/components/common/media/svg.tsx
src/index.tsx
src/utils/svg-utils.tsx

The SVG-related components didn't have any types for their props, so they were susceptible to a lot of errors. This change adds typing to their props so that errors can be caught preemptively.

Add prop types to the SVG-related components

---

src/components/Problems/Problems.tsx
src/components/Problems/reducer.ts
src/components/common/FilterForm/FilterForm.tsx

A common use case for me is to use the filter feature when I'm already at an area and I want to find something to climb (decision paralysis). When I'm doing this, it's annoying to have so much stuff on my little phone screen - and most if it adds zero value because I'm *already at an area*.
This feature allows the user to scope their filtration to specific areas.
It also allows sections of the form to be reset individually.

Allow scoping filter to areas

---

src/@types/buldreinfo/index.d.ts
src/api.ts
src/components/Permissions.tsx
src/components/common/chart-grade-distribution/chart-grade-distribution.tsx

Begin to apply the Swagger-generated types to the existing API definitions. This also does some validation that the existing components weren't making bad assumptions about the types.
It turns out that `Permissions` was, in fact, doing this so I stopped there and made this PR.

Start to type the API definitions

---

src/components/Sector.tsx

Currently, the map only shows for sectors with markers. However, if there's polygon data (but no markers) the map is hidden. This shouldn't be the case.
This change adjusts the logic to show the map if there are markers _or_ polygon information.

fix: Show map for sectors with polygon data

---

src/@types/buldreinfo/index.d.ts
src/api.ts
src/components/About.tsx
src/components/Dangerous.tsx
src/components/Frontpage.tsx
src/components/Graph.tsx
src/components/Permissions.tsx
src/components/Problem/ProblemComments/ProblemComments.tsx
src/components/Webcams.tsx
src/components/common/activity/activity.tsx
src/components/common/chart-grade-distribution/chart-grade-distribution.tsx
src/components/common/tick-modal/tick-modal.tsx

This changes the default type of `useData(..)` from `any` to `unknown`. The implication of this is that typing isn't _required_ to initiate a request, but a type definition is now required to _use_ the result of the request.
This small change should introduce a "pit of success" for future queries by needing their types provided from the get-go.

Encforce typing of useData(..)

---

src/utils/use-local-storage.tsx

Change the type definitions around local storage from `any` to `unknown`. This shouldn't be a problem because the default should always be provided, but it helps inch us closer to enabling `@typescript-eslint/no-explicit-any`

Don't use "any" typing on local storage

---

src/components/AreaEdit/useAreaEdit.ts

The `ImageUpload` component has an optional `file` attribute, but the `useAreaEdit` wanted it to be required. This isn't necessary as its absence is appropriately-handled in the upload code.

Fix typing confusion around NewMedia / UploadedMedia

---

src/utils/lazyRetry.ts

In order to minimize initial load-time, the site utilizes
code-splitting. This works great, except that it can be a bit annoying
in actual use: if the app is redeployed between when the app was first
loaded and when the user attempts to navigate to a new-to-them section,
they'll need to reload the entire app for it to work. This is not only
visually disruptive, but it's also problematic, as the user won't
always have the best network.
Instead, utilize the `requestIdleCallback(..)` function to initiate a
prefetch when the browser is idle. This will allow the entire app (but
not its data) to be laoded ahead of time.
> **NOTE**: This is [not supported on all browsers][caniuse], so on
> where it isn't supported, we do a little hack and load the chunks
> after a random interval (1s - 2.5s …

Prefetch the various lazy-loaded chunks

---

src/components/Area.tsx
src/components/AreaEdit/AreaEdit.tsx
src/components/Problem/Problem.tsx
src/components/Sector.tsx
src/components/SectorEdit.tsx
src/components/Sites.tsx
src/components/common/leaflet/distance-math.tsx
src/utils/polyline.ts

There is a lot of polyline / polygon coordinate data in the different data models, and this is parsed all over the app. This change pulls out a `parsePolyline(..)` function to avoid copy/pasting this code throughout the app.

Extract a parsePolyline(..) helper function

---

src/components/AreaEdit/AreaEdit.tsx
src/components/AreaEdit/useAreaEdit.ts

In the aim of being friendly to developers, `useAreaEdit(..)` would always return an Area-shaped object. However, this caused problems with the map: when setting the initial zoom/center, it wouldn't be later overridden when the real data rolled in.
One way to do this is to recreate the map when the real data is loaded, but that's really flickery and not a great experience.
The better option was to properly return `undefined` until the data has, in fact, been loaded.

Correctly zoom when editing an area

---

src/components/AreaEdit/useAreaEdit.ts

3e40416a8ae5b introduced a bug where a new area couldn't be created (because the component was perpetually waiting for the data to load).
This addresses that by setting a default state when no load is expected.

Fix bug preventing creation of areas

---

.eslintrc.js
src/components/Area.tsx
src/components/ProblemEdit.tsx
src/components/Sector.tsx
src/components/common/activity/activity.tsx
src/components/common/chart/chart.tsx
src/components/common/media/media-edit-modal.tsx
src/components/common/problem-list/accordion-container.tsx
src/components/common/problem-list/problem-list.tsx
src/components/common/problem-section/problem-section.tsx
src/components/common/profile/profile-statistics.tsx
src/utils/use-leaflet-control.tsx

Define the last of the React component props. This doesn't make all of the prop definitions **complete** (some of the props are still defined as `any`), but it's a step in the right direction.
This also makes `react/prop-types` an ESLint error to avoid regressing on this.

Finish typing all of the component props

---

src/api.ts
src/components/Area.tsx
src/components/Problem/Problem.tsx
src/components/Sector.tsx
src/utils/useRedirect.tsx

The current redirect behavior is very endpoint-specific. This is a bit annoying to work with, and susceptible to errors.
Instead, have `useData(..)` check for the redirect logic and see if we should be somewhere else. This adds a `redirectUi` element to the returned object from `useData(..)` which the caller can choose to return if they'd like to (but the client will be redirected regardless).

chore: Centralize redirect behavior

---

src/components/Areas.tsx
src/components/Dangerous.tsx
src/components/Problem/Problem.tsx
src/components/Problems/Problems.tsx
src/components/Webcams.tsx
src/components/common/HeaderButtons/HeaderButtons.tsx
src/components/common/TableOfContents/ProblemsMap/ProblemsMap.tsx
src/components/common/TableOfContents/ProblemsMap/index.ts
src/components/common/TableOfContents/TableOfContents.tsx
src/components/common/leaflet/leaflet.tsx
src/components/common/leaflet/markers.tsx
src/components/common/profile/profile-statistics.tsx
src/components/common/profile/profile-todo.tsx

Make it easier to get a sense of where the different problems and sectors are when filtering the routes/problems by showing a live-updating map on the filter page.
This map will be off by default on mobile devices, as it might be too cluttered and/or battery-intensive and/or network-intensive. However, it can be easily enabled with one button press.

Restore the map on the filter page

---

src/api.ts
src/components/ProblemEdit.tsx
src/components/SectorEdit.tsx
src/components/common/leaflet/leaflet.tsx

When editing map data on the sector page, the map keeps zooming around, which is annoying. Instead, set the zoom once based on the initial data and then leave it as it was.

Fix auto-zoom weirdness on the sector edit

---

src/api.ts
src/components/SectorEdit/PolylineEditor.tsx
src/components/SectorEdit/PolylineMarkers.tsx
src/components/SectorEdit/SectorEdit.tsx
src/components/SectorEdit/ZoomLogic.tsx
src/components/common/leaflet/markers.tsx
src/utils/colors.ts
src/utils/polyline.ts

This change aims to improve the experience of editing the map data for a sector. Specifically:
1. When drawing an outline, show the user the different points and allow them to delete them individually.
2. When drawing an approach, do the same thing.
3. Improve the GPX upload UI a little bit.
4. Hide the polyline string format by default.
5. Give the points individual colors so that the user can identify which ones go with which tags.

Improve the sector map-editing experience

---

src/utils/polyline.ts

When a polyline (approach path, outline) has points back-to-back, it results in a duplicate key. There's no real reason for two identical points to exist back-to-back for these, so this change just drops the redundant ones.

Remove duplicate polyline points

---

src/components/Dangerous.tsx
src/components/Problems/Problems.css
src/components/Problems/Problems.tsx
src/components/common/FilterForm/FilterForm.tsx
src/components/common/TableOfContents/TableOfContents.tsx

The current filter page has a lot of information, and it's presented in the same way on all kinds of devices -- no matter how big the screen is.
This change introduces some CSS-powered responsiveness to the page. On large screens (laptops, desktops, possibly landscape tablets), better-utilize the screen real estate with a two-column layout. On phones, however, keep the stacked layout (and hide the filter by default).
| Device | Screenshot |
|:---|:---:|
| Desktop | ![image](https://github.com/jossi87/climbing-web/assets/418560/d1002fbc-1232-4123-afce-eee2b67cadbe) |
| iPad Air | ![image](https://github.com/jossi87/climbing-web/assets/418560/bd552248-4208-4787-a6f2-2b4d72d76fd4) |
| iPad mini | ![image](https://github.com/jossi87/climbing-web/assets/418560/362f59b1-18fc-42a7-b73e-1b728e4acc …

Introduce a responsive filter page

---

src/components/Problems/reducer.ts

There was as a bug where clicking "Clear filter" would clear everything except the filtered-for areas.
This fixes that.

Fix: clear areas when clearing the filter

---

src/api.ts
src/components/ProblemEdit.tsx
src/components/ProblemEditMedia.tsx
src/components/SectorEdit/SectorEdit.tsx

Continue chipping away at the legacy of data-fetching that happens outside of the `@tanstack/react-query` data-fetching setup by removing all of the various `getArea(..)`, `getSector(..)`, and `getProblem(..)` functions.

Replace get{Area,Sector,Problem}(..) with use[Thing](..)

---

src/api/utils.ts

When refactoring the `api` module in #123, I overlooked the fact that `fetch` needs to be pulled from `isomorphic-fetch` in order to work.

Use fetch from isomorphic-fetch

---

.prettierignore
src/@types/buldreinfo/swagger.d.ts
src/api/index.ts
src/api/operations.ts
src/api/utils.ts
src/components/Problems/Problems.tsx
src/components/common/profile/profile-statistics.tsx

Add return typing to the API operations, instead of `any` typing. This also introduces a centralized "download `.xlsx`" functionality since it was spread into the component logic.

Add typing to API operations

---

src/api/hooks.ts
src/api/index.ts
src/api/operations.ts
src/components/SectorEdit/SectorEdit.tsx

Do a little revamping of the display of the elevation that's under the current cursor when editing a sector. This is admittedly a bit of overkill, but it at least hides the debounce state logic from the component level and exposes a cleaner API.
By utilizing the `@tanstack/react-query` library, we can expose more information about the underlying data (ie, is it being fetched or not).
And, on the off chance that the user ever requested the _exact same latitude & longitude_, it'd be filled instantly from cache!

Spruce up the elevation display

---

src/api/hooks.ts
src/api/index.ts
src/api/operations.ts
src/components/Area.tsx
src/components/Areas.tsx
src/components/Graph.tsx
src/components/Sector.tsx
src/components/common/chart-grade-distribution/chart-grade-distribution.tsx

Create a `useGradeDistribution(..)` hook to migrate the grade distribution fetching to the `@tanstack/react-query` data-fetching setup for enhanced caching & so on.
This also changes the API of the `ChartGradeDistribution` component to get rid of the unnecessary props, so it is more obvious how to use it.

Migrate getGradeDistribution to react-query

---

src/api/hooks.ts
src/api/index.ts
src/api/operations.ts
src/components/common/user-selector/user-selector.tsx

Migrate the `getUserSearch()` operation to `useUserSearch()` to benefit from the caching of the data-fetching library. This makes every user selector _substantially_ faster to load.

Migrate getUserSearch to react-query

---

src/api/hooks.ts

The upgrade to react-query v5 made some of our previous type fixings obsolete and we can remove our workaround -- yay!

chore: Remove TODO from react-query upgrade

---

src/components/SvgViewer/SvgRoute.tsx
src/utils/svg-utils.tsx

Utilize the `@types/svg-path-parser` package to add helpful typing to the parsed SVG output.
This also shifts around some code to make it a _very little_ bit easier to follow.

chore: Fix typing around SVG parsing

---

src/components/Problems/reducer.ts
src/components/common/FilterForm/FilterForm.tsx
src/components/common/FilterForm/YearSelect/YearSelect.tsx
src/components/common/FilterForm/YearSelect/index.ts
src/components/common/meta/index.ts
src/components/common/meta/meta.tsx

The first ascent year filter control is just like the grades: a ranged value. This change follows the convention already introduced by the grades, and uses a `RangeSlider` for the input, instead of separate drop-down inputs.
There's _possibly_ an opportunity for code reuse, but it gets a bit tricky -- while the controls look visually similar, they have different behaviors internally. Combining them might make sense, but it also might not. I left a comment in there for a future explorer to consider on a rainy day :)

feat: Use a RangeSlider for FA year filtering

---

package.json
src/components/Problems/Problems.tsx
src/components/Problems/reducer.ts
src/components/common/FilterForm/FilterForm.tsx
src/components/common/FilterForm/YearSelect/YearSelect.tsx
src/components/common/TableOfContents/TableOfContents.tsx
src/components/common/meta/meta.tsx
src/react-range-slider-input.d.ts
yarn.lock

We (currently) don't use TypeScript in strict mode, which results in a lot of _probably_-okay errors slipping through. However, it leads to more of a development struggle as static analysis is harder.
For this change, I uncommented `// strict: true,` in the `tsconfig.json` file and started fixing errors. For this pass, I focused on the errors in the general vicinity of the `/problems` route.
More to come in other PRs :)

chore: Fix some strict-mode TypeScript errors

---

eslint.config.js
package.json
src/utils/use-leaflet-control.tsx
yarn.lock

During the eslint upgrade, the `react` and `react-hooks` ESLint plugins were dropped because they didn't support the new ESLint config format. They still don't support the new format (yet) but this uses the `@eslint/compat` package to bring them in.

chore: Re-add react & react-hooks ESLint rules

---

src/components/Problems/reducer.ts

I'm getting errors about invalid event envelopes in the console that I missed in development - I guess I'm misusing the `captureEvent(..)` API (which isn't really documented). This switches the code to use the tried-and-true `captureMessage(..)` API instead.

fix: Use Sentry messages instead of events

---

src/components/Problems/Problems.tsx

The `/problems` component was written to show a loading spinner while fetching the data .. but the check for "are we loading?" was incorrect.
This change fixes the check so that we get the appropriate UI again.

fix: Show a loading indicator on /problems

---

src/components/common/FilterForm/GradeSelect/GradeSelect.tsx
src/components/common/meta/meta.tsx

It's a bit counter-intuitive to have the Grades slider be low-on-right -- in the Western hemisphere, we read from left-to-right, so it's more natural to have the lower grades on the left and the higher grades on the right.

fix: Flip the grade slider

---

src/components/Area.tsx

Conditional rendering with `{foo && <Bar />}` works great -- as long as `foo` is _guaranteed_ to be either `null`, `false`, or `undefined`. However, once you throw in a number, it gets complicated:
```ts
false && "foo"
```
React will see this as "render `false`" and render nothing. However:
```ts
0 && "foo"
```
This will render a JSX node of `0`, instead of nothing.
This change does a cleanup of the `Area` component, as the bug was observed there:
| Bug | Fix |
|:---:|:---:|
| ![image](https://github.com/jossi87/climbing-web/assets/418560/801978e0-551c-4ea9-a623-8d20538378e7) | ![image](https://github.com/jossi87/climbing-web/assets/418560/d682fed0-de0a-4751-a311-420ee73c48ff) |
I'll look to see if there's an ESLint rule we can add to prevent this pattern in the future, rather than having …

fix: Correct displayed route count

---

src/api/utils.ts
src/components/ProblemEdit.tsx
src/components/common/problem-section/problem-section.tsx
src/components/common/user-selector/user-selector.tsx

Fix another batch of errors when `strict: true` is enabled in `tsconfig.json` - this time, it's focused around `ProblemEdit`.
There should be no change in functionality - only fewer TS errors when strictmode is enabled. (However, it's hard to guarantee that - there's a lot of functionality, and very few tests)

chore: Fix TS strict errors around ProblemEdit

---

src/components/SectorEdit/PolylineEditor.tsx
src/components/SectorEdit/PolylineMarkers.tsx
src/components/SectorEdit/ProblemOrder.tsx
src/components/SectorEdit/SectorEdit.tsx
src/components/SectorEdit/ZoomLogic.tsx
src/components/SectorEdit/index.ts
src/components/common/leaflet/geo-utils.tsx

Focusing on `SectorEdit`, set `strict: true` in `tsconfig.json` and fix the detected errors.
This shouldn't cause any changes to user-visible behavior (none were noticed in my local testing, though I can't promose it was 100% thorough). However, there are some under-the-hood improvements with Sentry reporting various "WTF?"-type situations, if they should occur.

chore: Fix TS strict errors around SectorEdit

---

src/api/hooks.ts

The `useSvgEdit(..)` hook didn't correctly account for the case where the media doesn't already have data. In these cases, it would early-return `undefined` to avoid attempting to parse missing data. However, it should be returning an object that is valid, instead.

fix: Handle drawing the first topo line

---

src/components/Area.tsx
src/components/Problem/Problem.tsx
src/components/common/leaflet/leaflet.tsx
src/components/common/leaflet/markers.tsx

The current parking markers are buggy, and not terribly helpful.
- When looking at an area, the "parking marker" is actually a bunch of markers all stacked up on top of each other - one for each sector. Clicking on it will navigate you to a pseudo-random sector, which isn't what I want.
- When looking at a sector, the parking marker doesn't actually do anything.
- When looking at a problem, the parking marker will navigate you to that same problem. Again, not helpful.
Instead, this change replaces all navigation with a popup. This popup contains a button to open Google Maps pointed to that location. The intention of this feature is to allow mobile users to get driving directions/estimates to the parking area (desktop users too, but that's possibly less-important).

feat: Add a navigation popup to parking markers

---

src/utils/use-local-storage.tsx

Today, if you browse an area, go to the problems view and changes filters like Group by, Order by etc, it will reset back to default values the next time you browse away and back.
This is due to bug in the use-local-storage that ends up saving all the filter values to session storage, but tries to read them from localstorage, and since they are not there, the default values will be returned.

Fix issue with state not being saved between pages

---

src/components/common/TableOfContents/ProblemsMap/ProblemsMap.tsx

For some reason, this boolean is set to false, making it hard to use the map to navigate to specific problems. Is there a reason why this is disabled?

fix: Enable clicking on sectors on the map to navigate

---

src/components/common/media/media-modal.tsx

There seems to be an issue with the current onProgress as it caused the video player to loop back to the beginning each time it reached the buffer. Also skipping within the video has not really worked that great on the site before the video was fully loaded. They both seem to be fixed within my localhost testing.

Updated ReactPlayer to fix video player loop bug and improved skipping. Also updated video size.
